### ISSUE TITLE
[js] refine `parentId` typing on `MessageMetadata`

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/tbdex-protocol#101]
First message in a thread will not have a parent, hence `parentId` should either be optional or nullable. It's currently nullable.

consider:
```
export type TbDEXMessage<T extends keyof MessageTypes> = MessageMetadata & {
  type: T
  parentId: T extends 'rfq' ? never : string
  body: MessageTypes[T]
}
```
(Thanks @mistermoe!)

**Comment by mistermoe** [comment]
closing bc https://github.com/TBD54566975/tbdex-protocol/issues/138#issuecomment-1711132321
