### ISSUE TITLE
PFI side of SDK should automatically generate a DID on startup and anchor it for discovery

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/tbdex-protocol#153]
This can be in the mock/sample PFI - and it should register the PFIs publicly addressable endpoint in the did doc that is registered. This could also be a command line utility to generate a DID and anchor it for PFI implementations that are in other languages

**Comment by mistermoe** [comment]
implemented in [tbdex-mock-pfi](https://github.com/tbd54566975/tbdex-mock-pfi)!
