### ISSUE TITLE
[Feature Request] Kotlin Multiplatform support

### ISSUE THREAD

**Issue by nrobi144** [TBD54566975/tbdex-protocol#70]
## Why?
The current tbdex-protocol is easy to consume in **JVM-based projects**. Providing better inclusion for other platforms, including JS, Apple ecosystem, etc... would favour the reusability of this protocol

## What?
Kotlin offers first-class support for JVM-based projects. Additionally, Kotlin has three compilers (Kotlin/Native, Kotlin/JS, and Kotlin/JVM) with Kotlin/Wasm in the works. 
Leveraging the above three compilers Kotlin Multiplatform provides the tooling, which can be used to reuse business logic across these platforms, while still providing native solutions where needed.

Thus restructuring the current projects in a Kotlin Multiplatform manner could increase the reusability of this protocol across non-JVM platforms.

### How?
A couple of changes this would require:
- [ ] Refactor Java classes to Kotlin
- [ ] Add KMP support in `build.gradle`
- [ ] Migrate to platform agnostic Kotlin solutions (less JVM dependencies). For ex. [kotlinx-serialization](https://github.com/Kotlin/kotlinx.serialization) instead of Gson
- [ ] Support as many targets as possible ([See the full list of targets supported by KMP](https://kotlinlang.org/docs/multiplatform-dsl-reference.html#targets))

A couple of resources:
- https://kotlinlang.org/docs/multiplatform.html#full-stack-web-applications 
- https://github.com/halcyonmobile/MultiplatformPlayground -> targets the following platforms JVM (Backend), Android, iOS, macOS

Happy to provide an example PR if needed :)

**Comment by mistermoe** [comment]
@nrobi144 100% agreed. our main aim is to support as many platforms as possible and Kotlin would definitely help us make strides in that direction. 

The central aim of this repo was to act as a playground to help us quickly prototype ideas and iterate on them. we'll be archiving it soon and starting fresh

**Comment by nrobi144** [comment]
@mistermoe awesome. Happy to help out if needed
I've started a [discussion](https://forums.tbd.website/t/best-tooling-for-wide-platform-support/97) around platform-support and KMP on the forums

**Comment by michaelneale** [comment]
thanks @nrobi144 - mobile moved to https://github.com/TBD54566975/ssi-sdk-mobile - but I think kotlin will be making a comback. 

How solid is kotlin multiplatform for ios these days?

**Comment by nrobi144** [comment]
@michaelneale It's not the same as using native iOS tooling. It's the best multi-platform tool currently. At [octopus.energy ](https://octopus.energy) we've had multiple iOS apps in production for 1-2 years, using 70-80% shared Kotlin code.

**Comment by michaelneale** [comment]
@nrobi144 really interesting. Firstly - octopus energy is interesting but that is a topic for another time. 
Secondly - do you have any open source repos or all close? 
Thirdly are you on tbd discord? If so find me there as michaelneale#2087 would love to learn more.

**Comment by nrobi144** [comment]
@michaelneale I think these are some of the best open-source examples:

- https://github.com/joreilly/PeopleInSpace
- https://github.com/touchlab/KaMPKit

And here are some case studies from some mobile teams: https://kotlinlang.org/lp/mobile/case-studies/

I'll reach out on discord :)

**Comment by michaelneale** [comment]
thanks @nrobi144 - will close this as most of the code is now in the web5-js and dwn-sdk-js repos (which is where multiplatform may be relevant as a port)
