### ISSUE TITLE
Adding List of Offerings as a message type

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex-protocol#75]
I think it could be useful to define a list of currency pairs and required VCs that each PFI is willing to trade with individuals. 

I haven't given much thought yet whether fee structure should be a part of this message type, but here's a small example I came up with of what the JSON response might look like from a simple PFI who only offers BTC<>USD exchange, that offers different rates, based different VC requirements. I'd like to know if I'm on the right path, or if we should come up with something totally different, or if having this message type even makes sense!

The list of offerings describe:
- Currency pair
- Each Offer of a currency pair contains rate and the corresponding list of required VCs

```javascript
{
  "offerings": [
    {
      "source_currency": "USD",
      "target_currency": "BTC",
      "offers": [
        {
          "conversion_rate": 0.000036,
          "required_presentation_definitions": [{ schema: "KYC" }, { schema: "Credit_Card" }]

        },
        {
          "conversion_rate": 0.000038,
          "required_presentation_definitions": [{ schema: "KYC" }, { schema: "Debit_Card" }, { schema: "Age" }]

        }
      ]
    }
  ]
}
```

~~i am realizing that `required_vcs` is somewhat contrived - i think there's a lot more to VCs than just saying "yeah, just give me a KYC VC". a better way to tell the individual (Alice) what kind of VC is accepted would be to expose the KYC VC Schema that the PFI accepts, as well as the Presentation Definition and Request.~~

edit: i've gone ahead and removed `required_vcs` and added `required_presentation_definitions` to reflect the changes based on above comment

cc @michaelneale

**Comment by michaelneale** [comment]
yes this is the sort of thing I was thinking @jiyoontbd. There may be cases where PFIs don't want to offer specific rates, or even advertise what VCs they would accept (and it can be as simple as that yeah). As to how this fits into tbdex, I think 2 ways spring to mind: 

1) the did when created specifies an endpoint which can be accessed to get this JSON - and it is up to the PFI to implement it. It is then out of band of any DWN/tbdex messages
2) we have a new tbdex message type added to the protocol which is RequestOffers and Offer (similar to RFQ results in many Quotes - RequestOffer results in many Quotes).

**Comment by jiyoontbd** [comment]
in my mind, this JSON is the response of a GET request from Alice's wallet, which takes no arguments. would it still fit into the tbdex way of things, per option 2? 

> RFQ results in many Quotes

i was thinking that 1 RFQ -> 1 Quote... do you mean many Quotes from many PFIs? or many Quotes from 1 PFI?

also, as an aside how can i tell by reading a protocol that there's a one to many relationship?

**Comment by jiyoontbd** [comment]
also, i wanted to call out that, instead of this "endpoint" returning a list of VCs for each offering, maybe it should offer some way to let Alice know of the Presentation Request/Definition that the PFI is expecting, so that Alice (or her wallet) can learn how to format her VC into a proper Presentation Submission.

**Comment by michaelneale** [comment]
RFQ could result in many quotes (with different identity or settlement options for alice to choose from - saves asking multiple times).

**Comment by michaelneale** [comment]
and yes - that could result in option 2 working: Alice asks via tbdex what is on offer. The advantage of having it in tbdex types is that keeps the interfaces in one place, that PFIs need to care about (vs some is via web5, some via HTTP etc).

**Comment by jiyoontbd** [comment]
> and yes - that could result in option 2 working: Alice asks via tbdex what is on offer. The advantage of having it in tbdex types is that keeps the interfaces in one place, that PFIs need to care about (vs some is via web5, some via HTTP etc).

100% agree with this. which brings my next point - 

> RFQ could result in many quotes (with different identity or settlement options for alice to choose from - saves asking multiple times).

by having offering a tbdex message type that PFI has make visible somehow, we'd be "front-loading" the work of Alice getting bids from PFIs, by Alice simply aggregating offers from PFIs that she's interested in. Maybe there's a service (or her wallet does this behind the scenes) that gets offers from n PFIs, filters them down to the exchange she wants to make (i.e. her USD for their BTC) and what kind of presentation definition is required (i.e. KYC VC), and what kind of payment instrument she has available.

Once she identifies an offer that she likes, that's the time at which she'd send in an RFQ specifically to the PFI of the offer. This implies that the RFQ <-> Quote is only done between Alice and 1 PFI, not Alice and n PFIs as you mentioned above. 

Frontloading this work by PFI having offers and Alice "window-shopping" for them would achieve the same goal of Alice not having to ask multiple times.

**Comment by jiyoontbd** [comment]
i'm closing this issue since #77 addresses it !
