### ISSUE TITLE
question about the PFI discovery process

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex-protocol#76]
The [TBD whitepaper](https://tbdex.io/whitepaper.pdf) has a section on PFI Discovery that describes several different ways of individuals finding PFIs who can facilitate the financial transaction that the individual wants.

In addition to PFI DIDs being available to individuals, there should be a way for PFIs to "advertise" the specific financial services they provide, so their offerings can be indexed and filtered, either by an individual, a provider, or a DID directory. i.e. When a PFI DID resolves to a DID document, the DID document can include a public endpoint that returns [a list of offerings, which could be a tbdex protocol message type](https://github.com/TBD54566975/tbdex-protocol/issues/75)? 

cc @michaelneale

**Comment by michaelneale** [comment]
yes - I have been thinking about this. You could have a Directory protocol and let any PFIs write to it - but if that is open to anyone that means that a single DID would contain a lot of records and become a bit unmanageable. 

Given that, some options I have been thinking about: 
1) crawl the did:ion types. This can be done by using a did:ion service (like TBD hosts, or MSFT, or anyone can run one) and then accessing a url like `https://ion.tbddev.org/didtype/003` - using an appropriate type from https://github.com/decentralized-identity/sidetree/blob/master/docs/type-registry.md - there could be a type for PFIs. This would give a list of did urls that can then be accessed (a flat list) - anchored dids. 

2) Use some other permissionless system like a nostr relay to listen for PFIs advertising their existence and potential offerings: https://gist.github.com/michaelneale/cdfc94c0e5d91006e756e69bb55a04aa. Publishing to a relay is permissionless, but there would need to be listening to appropriate events for a message of certain types (and then extract the did from that - also disover other recommended relays and PFIs). This has many scaling challenges but is an example of something permissionless of the top of my head. 

I expect some combination of the above is needed, hopefully with many parties offering indexing and discovery services that is robust in a global market.
