### ISSUE TITLE
Remove `expiresTime` in the top level tbdex message key in README 

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex-protocol#83]
> there's an `expiresTime` in the current readme - are we not using that field now? (tbh i was never 100% sure what that field would be for. the only time we use expiry is when we give out a Quote, and that would live in the `body` field anyway).

_Originally posted by @jiyoontbd in https://github.com/TBD54566975/tbdex-protocol/pull/78#discussion_r1228989916_

**Comment by phoebe-lew** [comment]
done in #84
